import type { Metadata } from 'next';
import './styles/globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import ReduxProvider from './ReduxProvider';


export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<ReduxProvider>
					<body className={`antialiased`}>{children}</body>
				</ReduxProvider>
			</html>
		</ClerkProvider >
	);
}



